---
- hosts: ukubernetes-master-nodes,ukubernetes-worker-nodes 

  vars:
   ubpackages:
   - docker*
   - kubeadm
   - kubectl
   - kubelet

  tasks:
  - name: remove kubeadm
    command: "kubeadm reset -f"

  - name: Uninstalling kubernetes related packages
    yum:
     name: "{{ item }}"
     state: absent 
    with_items: "{{ ubpackages }}"

  - name: Removing required files
    file:
     path: "{{ item }}"
     state: absent
    with_items:
    - /etc/kubernetes/
    - /var/lib/etcd/
    - $HOME/.kube/

